FROM nginx:latest
RUN rm /etc/nginx/conf.d/*
COPY ./web3.conf /etc/nginx/conf.d
COPY ./lb3.conf /etc/nginx/conf.d
RUN mkdir /var/www
RUN mkdir /var/www/mess31.com
RUN mkdir /var/www/mess32.com
RUN mkdir /var/www/mess33.com
COPY ./mess31.html /var/www/mess31.com/index.html
COPY ./mess32.html /var/www/mess32.com/index.html
COPY ./mess33.html /var/www/mess33.com/index.html
